# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 42bfb06b3e992197089e842910bb6b614e25715d9eab94779cb263db6c8f5ef143567fbd709dc1fb53428b832e8494cde26eabff96e4ef4322dfe7d424f64bca

test:
  secret_key_base: df9427a6b1d51c87c26ff16ac523242bb0c80d42eccc1fa20ea3e4540bbc58ca0d7b8cfa9296467bf6a22ca33ae62cfe0f46b686e74a39e271eeda2c13bda4f7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
